In [1]:
import pandas as pd
import sqlalchemy as sa

import numpy as np

import axelrod as axl

import opt_mo
import random


In [2]:
engine = sa.create_engine("sqlite:///../data/without_gambler/main.db")


In [3]:
connection = engine.connect()


In [4]:
df = pd.read_sql("experiments", connection)


In [5]:
def get_histories(seed, function):
    axl.seed(seed)
    opponents = [[random.random() for _ in range(4)] for _ in range(2)]

    _, history, _ = opt_mo.get_evolutionary_best_response(
        opponents=opponents, best_response_function=function
    )

    return history


**A small example**

In [6]:
engine = sa.create_engine("sqlite:///../data/main.db")


In [7]:
connection = engine.connect()


In [8]:
small_example = pd.read_sql("experiments", connection)


In [9]:
small_example


exp_index  first_opponent_q_1  first_opponent_q_2  first_opponent_q_3  \
0          8            0.226706            0.962295            0.126331   
1          9            0.463007            0.373312            0.138539   

   first_opponent_q_4  second_opponent_q_1  second_opponent_q_2  \
0            0.704817             0.085185             0.247441   
1            0.866562             0.006435             0.502782   

   second_opponent_q_3  second_opponent_q_4  mem_one_p_1  \
0             0.999129             0.209398            0   
1             0.898298             0.080815            0   

           ...            mem_one_cycle_length  reactive_p_1  reactive_p_2  \
0          ...                               4      0.000000      0.160720   
1          ...                               1      0.000086      0.196509   

   reactive_p_3  reactive_p_4  evol_reactive_p_1  evol_reactive_p_2  \
0      0.000000      0.160720           0.000000           0.000000   
1      0.000086      0.196509           0.001243           0.067105   

   evol_reactive_p_3  evol_reactive_p_4  reactive_cycle_length  
0           0.000000           0.000000                      1  
1           0.001243           0.067105                      2  

[2 rows x 27 columns]

In [10]:
seeds = df["exp_index"][df["mem_one_cycle_length"] > 1].values


In [11]:
reactive_seeds = df["exp_index"][df["reactive_cycle_length"] > 1].values


In [12]:
df.describe()


exp_index  first_opponent_q_1  first_opponent_q_2  first_opponent_q_3  \
count  100.000000          100.000000          100.000000          100.000000   
mean    49.500000            0.465369            0.504752            0.511140   
std     29.011492            0.277173            0.280757            0.305147   
min      0.000000            0.012278            0.011655            0.008480   
25%     24.750000            0.233713            0.257310            0.203881   
50%     49.500000            0.451612            0.514548            0.557020   
75%     74.250000            0.678346            0.712386            0.764458   
max     99.000000            0.978355            0.983214            0.997728   

       first_opponent_q_4  second_opponent_q_1  second_opponent_q_2  \
count          100.000000           100.000000           100.000000   
mean             0.497352             0.499797             0.528246   
std              0.293344             0.312052             0.268276   
min              0.004392             0.000452             0.011036   
25%              0.247797             0.222873             0.352089   
50%              0.461747             0.510810             0.515368   
75%              0.777694             0.797417             0.730129   
max              0.998631             0.995061             0.999020   

       second_opponent_q_3  second_opponent_q_4  mem_one_p_1  \
count           100.000000           100.000000   100.000000   
mean              0.502436             0.468291     0.244706   
std               0.278872             0.275244     0.398870   
min               0.000403             0.008806     0.000000   
25%               0.287986             0.207675     0.000000   
50%               0.498104             0.461888     0.000000   
75%               0.711546             0.696529     0.395951   
max               0.999129             0.973859     1.000000   

               ...            mem_one_cycle_length  reactive_p_1  \
count          ...                      100.000000    100.000000   
mean           ...                        1.780000      0.070020   
std            ...                        2.780088      0.256416   
min            ...                        1.000000      0.000000   
25%            ...                        1.000000      0.000000   
50%            ...                        1.000000      0.000000   
75%            ...                        1.250000      0.000000   
max            ...                       25.000000      1.000000   

       reactive_p_2  reactive_p_3  reactive_p_4  evol_reactive_p_1  \
count    100.000000    100.000000    100.000000         100.000000   
mean       0.125518      0.070020      0.125518           0.079974   
std        0.266964      0.256416      0.266964           0.272511   
min        0.000000      0.000000      0.000000           0.000000   
25%        0.000000      0.000000      0.000000           0.000000   
50%        0.000000      0.000000      0.000000           0.000000   
75%        0.068671      0.000000      0.068671           0.000000   
max        1.000000      1.000000      1.000000           0.999962   

       evol_reactive_p_2  evol_reactive_p_3  evol_reactive_p_4  \
count         100.000000         100.000000         100.000000   
mean            0.040106           0.079974           0.040106   
std             0.105970           0.272511           0.105970   
min             0.000000           0.000000           0.000000   
25%             0.000000           0.000000           0.000000   
50%             0.000000           0.000000           0.000000   
75%             0.000000           0.000000           0.000000   
max             0.739442           0.999962           0.739442   

       reactive_cycle_length  
count             100.000000  
mean                1.290000  
std                 0.956583  
min                 1.000000  
25%                 1.000000  
50%                 1.000000  
75%  

**Explore output**

In [31]:
experiment_seed = df["exp_index"].values


In [35]:
experiments_with_big_cycle = df[df["mem_one_cycle_length"] > 1]


In [19]:
axl.seed(10)
opponents = [[random.random() for _ in range(4)] for _ in range(2)]


In [20]:
big_cycle.iloc[2][1:5] == opponents[0]


first_opponent_q_1    True
first_opponent_q_2    True
first_opponent_q_3    True
first_opponent_q_4    True
Name: 10, dtype: bool

In [21]:
big_cycle.iloc[2][5:9] == opponents[1]


second_opponent_q_1    True
second_opponent_q_2    True
second_opponent_q_3    True
second_opponent_q_4    True
Name: 10, dtype: bool

In [22]:
best_response = opt_mo.get_memory_one_best_response(opponents)


In [23]:
best_response


array([0.        , 0.        , 0.        , 0.99999999])

In [24]:
big_cycle.iloc[2][9:13]


mem_one_p_1    0.0
mem_one_p_2    0.0
mem_one_p_3    0.0
mem_one_p_4    1.0
Name: 10, dtype: float64

In [25]:
best_evol_response = opt_mo.get_evolutionary_best_response(
    opponents, opt_mo.get_memory_one_best_response
)


Next generation.
Next generation.
Next generation.
Next generation.
Next generation.
Next generation.
Next generation.
Next generation.
Next generation.


In [26]:
opt_mo.evolutionary_best_response.get_repeat_length_in_history(best_evol_response[-2])


2

In [27]:
best_evol_response[-1]


2

In [28]:
best_evol_response[0]


array([0.        , 0.        , 0.        , 0.45712898])

In [29]:
big_cycle.iloc[2][13:17]


evol_mem_one_p_1    0.000000
evol_mem_one_p_2    0.000000
evol_mem_one_p_3    0.000000
evol_mem_one_p_4    0.457129
Name: 10, dtype: float64

In [31]:
axl.seed(9)
opponents = [[random.random() for _ in range(4)] for _ in range(2)]


In [32]:
big_cycle.iloc[1][1:5] == opponents[0]


first_opponent_q_1    True
first_opponent_q_2    True
first_opponent_q_3    True
first_opponent_q_4    True
Name: 9, dtype: bool

In [34]:
big_cycle.iloc[1][5:9] == opponents[1]


second_opponent_q_1    True
second_opponent_q_2    True
second_opponent_q_3    True
second_opponent_q_4    True
Name: 9, dtype: bool

In [35]:
best_response = opt_mo.get_memory_one_best_response(opponents)


In [36]:
best_response


array([0.        , 0.        , 0.        , 0.46105412])

In [37]:
big_cycle.iloc[1][9:13]


mem_one_p_1    0.000000
mem_one_p_2    0.000000
mem_one_p_3    0.000000
mem_one_p_4    0.461055
Name: 9, dtype: float64

In [38]:
best_evol_response = opt_mo.get_evolutionary_best_response(
    opponents, opt_mo.get_memory_one_best_response
)


Next generation.
Next generation.
Next generation.
Next generation.
Next generation.
Next generation.
Next generation.
Next generation.
Next generation.
Next generation.
Next generation.
Next generation.


In [39]:
opt_mo.evolutionary_best_response.get_repeat_length_in_history(best_evol_response[-2])


1

In [40]:
best_evol_response[-1]


1

In [41]:
best_evol_response[0]


array([0.        , 0.        , 0.        , 0.19225855])

In [43]:
big_cycle.iloc[1][13:17]


evol_mem_one_p_1    0.00000
evol_mem_one_p_2    0.00000
evol_mem_one_p_3    0.00000
evol_mem_one_p_4    0.19223
Name: 9, dtype: float64

In [44]:
big_cycle.iloc[1][13:18]


evol_mem_one_p_1        0.00000
evol_mem_one_p_2        0.00000
evol_mem_one_p_3        0.00000
evol_mem_one_p_4        0.19223
mem_one_cycle_length    3.00000
Name: 9, dtype: float64

In [ ]:
def check_out_put(seed):
    axl.seed(seed)
    opponents = [[random.random() for _ in range(4)] for _ in range(2)]

    row = experiments_with_big_cycle[
        experiments_with_big_cycle["exp_index"] == 8
    ].values[0]

    assert np.allclose(row[1:5], opponents[0])
    assert np.allclose(row[5:9], opponents[1])

    best_response = opt_mo.get_memory_one_best_response(opponents)
    assert np.allclose(row[9:13], best_response)
    best_evol_response = opt_mo.get_evolutionary_best_response(
        opponents, opt_mo.get_memory_one_best_response
    )
    assert (
        opt_mo.evolutionary_best_response.get_repeat_length_in_history(
            best_evol_response[-2]
        )
        == best_evol_response[-1]
    )
    assert np.allclose(best_evol_response[0], row[13:17])


In [57]:
check_out_put(8)


**Creating histories**

In [217]:
mem_histories = []
for seed in seeds:
    mem_histories.append(get_histories(seed, opt_mo.get_memory_one_best_response))


In [218]:
histories = []
for seed in reactive_seeds:
    histories.append(
        get_histories(seed, opt_mo.get_reactive_best_response_with_bayesian)
    )


In [205]:
columns = [
    ["seed: {} p: {}".format(seed, prop) for prop in range(1, 5)] for seed in seeds
]
columns = [item for sublist in columns for item in sublist]


In [206]:
count = 0
series = []
for i, column in enumerate(columns):
    if i % 4 == 0:
        count += 1

    series.append(pd.Series([item[i % 4] for item in mem_histories[count - 1]]))


In [207]:
df_mem_history = pd.concat(series, ignore_index=True, axis=1)
df_mem_history.columns = columns


In [215]:
histories = mem_histories.append(get_histories(95, opt_mo.get_memory_one_best_response))


Next generation.


In [216]:
histories


In [208]:
df_mem_history.to_csv("../data/mem_histories.csv")


**Reactive**

In [27]:
columns = [
    ["seed: {} p: {}".format(seed, prop) for prop in range(1, 5)]
    for seed in reactive_seeds
]


In [176]:
columns = [item for sublist in columns for item in sublist]


In [171]:
count = 0
series = []
for i, column in enumerate(df_history.columns):
    if i % 4 == 0:
        count += 1

    series.append(pd.Series([item[i % 4] for item in histories[count - 1]]))


In [178]:
df_history = pd.concat(series, ignore_index=True, axis=1)
df_history.columns = columns


In [181]:
df_history.to_csv("../data/reactive_histories.csv")


**Visualation**

In [ ]:
mem_histories = pd.read_csv("../data/mem_histories.csv", index_col=0)


In [ ]:
p_ones_col = mem_histories.columns[mem_histories.columns.str.contains(pat="p: 1")]
p_twos_col = mem_histories.columns[mem_histories.columns.str.contains(pat="p: 2")]
p_threes_col = mem_histories.columns[mem_histories.columns.str.contains(pat="p: 3")]
p_fours_col = mem_histories.columns[mem_histories.columns.str.contains(pat="p: 4")]


In [ ]:
for col_one, col_two, col_three, col_four in zip(
    p_ones_col, p_twos_col, p_threes_col, p_fours_col
):

    points = mem_histories[[col_one, col_two, col_three, col_four]].values
    fig, ax = plt.subplots(nrows=2, ncols=2, figsize=(10, 6.5))
    for i in range(4):
        axes = (int(i / 2), i % 2)
        ax[axes].plot(points[i], linestyle="--", marker="o"),
        ax[axes].set_title(r"Covergance of $p^{(t)}_%s$" % (i + 1))
        ax[axes].set_ylim(-0.05, 1.05)

    fig.tight_layout()


In [ ]:
reactive_histories = pd.read_csv("../data/reactive_histories.csv", index_col=0)


In [ ]:
p_ones_col = reactive_histories.columns[
    reactive_histories.columns.str.contains(pat="p: 1")
]
p_twos_col = reactive_histories.columns[
    reactive_histories.columns.str.contains(pat="p: 2")
]


In [ ]:
for col_one, col_two in zip(p_ones_col, p_twos_col):
    points = reactive_histories[[col_one, col_two]]
    points = points.dropna().values

    fig, ax = plt.subplots()
    for i in range(len(points)):
        x = points[i][0]
        y = points[i][1]
        ax.plot(x, y, "bo")
        ax.text(x * (1 + 0.01), y * (1 + 0.01), i, fontsize=12)
